import Hero from '@/templates/Hero'
import Head from 'next/head'
import Image from 'next/image'
import herobg from '../assets/images/bg.png'
import Header from '@/templates/Header'

export default function Home() {
  return (
    <>
      <Head>
        <title>SwitchOff</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <img src={herobg.src} className='temp' />
        <Header />
        <Hero />
      </main>
    </>
  )
}
