import Hero from '@/templates/Hero'
import Head from 'next/head'
import Image from 'next/image'
import herobg from '../assets/images/bg.png'
import Header from '@/templates/Header'
import { AnimatePresence } from 'framer-motion'
import dynamic from 'next/dynamic';
const DynamicModal = dynamic(() => import('@/templates/Property/PropertyModal'), { ssr: false });
import { atom, useAtom } from 'jotai'
import Destinations from '@/templates/Sections/Destinations'

//global states
export const propertyModalState = atom({
  open: false,
  propertyId: '',
  hotelId: ''
})

export const getPropetyModalState = atom((get) => get(propertyModalState))

export default function Home() {
  return (
    <>
      <Head>
        <title>SwitchOff</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <img src={herobg.src} className='temp' /> */}
        <AnimatePresence>
          <Header />
          <Hero />
          <Destinations />
          <DynamicModal />
        </AnimatePresence>
      </main>
    </>
  )
}
