import Head from 'next/head'
import Header from '@/templates/Header'
import { AnimatePresence } from 'framer-motion'
import { atom } from 'jotai'
import { BrowserView, MobileView} from 'react-device-detect'
import Footer from '@/templates/Footer/Footer'
import { getTermsnConditionsContent } from '@/api/hygraph'

//global states
export const propertyModalState = atom({
  open: false,
  propertyId: '',
  hotelId: ''
})

export const getPropetyModalState = atom((get) => get(propertyModalState))

export default function PrivacyPolicy({data}) {
  return (
    <>
      <Head>
        <title>Terms & Conditions | SwitchOff</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='tc-main'>
        {/* <img src={herobg.src} className='temp' /> */}
        <BrowserView>
        <AnimatePresence>
          <Header />
          <div className="container privacy-policy tc">
          <h1 style={{textAlign: 'center'}}>{data.title} for 
          <br />LITBIT TECHNOLOGIES PRIVATE LIMITED</h1>
            <br />
            <div dangerouslySetInnerHTML={{__html: data.content.html}} />
          </div>
          <Footer />
        </AnimatePresence>
        </BrowserView>
        <MobileView>
          <div>
          <h2>This Website is in Test mode and Only available on Desktop Browsers.</h2>
          </div>
        </MobileView>
      </main>
    </>
  )
}

export const getStaticProps = async () => {
  const data = await getTermsnConditionsContent()
  return {
    props: {
      data
    }
  }
}
